site_name: uv-cookie-proj
repo_url: https://github.com/bartev/uv-cookie-proj
site_url: https://bartev.github.io/uv-cookie-proj
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Bartev Vartanian
edit_uri: edit/main/docs/
repo_name: bartev/uv-cookie-proj
copyright: Maintained by <a href="https://bartev.com">bartev</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [uv_cookie_proj]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bartev/uv-cookie-proj
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/uv-cookie-proj

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
